# Generated by Django 4.2.9 on 2024-02-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_post_latest_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="post",
            name="preview",
        ),
    ]
